general.import = [ "~/.local/state/current/theme/alacritty.toml", 
  "~/.local/state/current/font/alacritty.toml"] 

[env]
TERM = "alacritty"

[window]
padding.x = 0
padding.y = 0
decorations = "None"

